return {
        {
                "catppuccin/nvim",
                enabled  = true,
                lazy     = false,
                name     = "catppuccin",
                priority = 1000,
                config   = function()
                        require("catppuccin").setup({
                                compile_path           = vim.fn.stdpath "cache" .. "/catppuccin",
                                flavour                = "mocha",
                                background             = {
                                        light = "latte",
                                        dark  = "mocha",
                                },
                                transparent_background = false,
                                show_end_of_buffer     = true,
                                term_colors            = true,
                                dim_inactive           = {
                                        enabled    = false,
                                        shade      = "dark",
                                        percentage = 0.15,
                                },
                                no_italic              = true,
                                no_bold                = false,
                                no_underline           = false,

                                custom_highlights      = function(colors)
                                        return {

                                                -------------------------------------------------------------------------------------------------------------------
                                                -- CMP

                                                CustomPmenu                      = { bg = colors.mantle },
                                                CustomBorder                     = { fg = colors.mantle, bg = colors.mantle },
                                                --Documentation
                                                CmpPmenu                         = { fg = colors.text, bg = colors.mantle },
                                                CmpBorder                        = { fg = colors.mantle, bg = colors.mantle },

                                                Pmenu                            = { fg = colors.text, bg = colors.mantle },
                                                PmenuSel                         = { fg = colors.flamingo, bg = colors.mantle },

                                                CmpItemAbbrDeprecated            = { fg = colors.maroon, bg = "NONE" },
                                                CmpItemAbbrMatch                 = { fg = colors.text, bg = "NONE", bold = true },
                                                CmpItemAbbrMatchFuzzy            = { fg = colors.text, bg = "NONE", bold = true },
                                                CmpItemMenu                      = { fg = colors.overlay0, bg = "NONE", bold = true },
                                                CmpItemKindField                 = { fg = colors.rosewater, bg = "NONE" },
                                                CmpItemKindProperty              = { fg = colors.rosewater, bg = "NONE" },
                                                CmpItemKindEvent                 = { fg = colors.rosewater, bg = "NONE" },
                                                CmpItemKindText                  = { fg = colors.lavender, bg = "NONE" },
                                                CmpItemKindEnum                  = { fg = colors.lavender, bg = "NONE" },
                                                CmpItemKindKeyword               = { fg = colors.lavender, bg = "NONE" },
                                                CmpItemKindConstant              = { fg = colors.yellow, bg = "NONE" },
                                                CmpItemKindConstructor           = { fg = colors.yellow, bg = "NONE" },
                                                CmpItemKindReference             = { fg = colors.yellow, bg = "NONE" },
                                                CmpItemKindFunction              = { fg = "#dce0e8", bg = "NONE" },
                                                CmpItemKindStruct                = { fg = "#dce0e8", bg = "NONE" },
                                                CmpItemKindClass                 = { fg = "#dce0e8", bg = "NONE" },
                                                CmpItemKindModule                = { fg = "#dce0e8", bg = "NONE" },
                                                CmpItemKindOperator              = { fg = "#dce0e8", bg = "NONE" },
                                                CmpItemKindVariable              = { fg = colors.text, bg = "NONE" },
                                                CmpItemKindFile                  = { fg = colors.text, bg = "NONE" },
                                                CmpItemKindUnit                  = { fg = colors.yellow, bg = "NONE" },
                                                CmpItemKindSnippet               = { fg = colors.yellow, bg = "NONE" },
                                                CmpItemKindFolder                = { fg = colors.yellow, bg = "NONE" },
                                                CmpItemKindMethod                = { fg = colors.text, bg = "NONE" },
                                                CmpItemKindValue                 = { fg = colors.text, bg = "NONE" },
                                                CmpItemKindEnumMember            = { fg = colors.text, bg = "NONE" },
                                                CmpItemKindInterface             = { fg = colors.teal, bg = "NONE" },
                                                CmpItemKindColor                 = { fg = colors.teal, bg = "NONE" },
                                                CmpItemKindTypeParameter         = { fg = colors.teal, bg = "NONE" },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- CMD

                                                NoiceCmdline                     = { bg = colors.base },
                                                NoiceCmdlinePopup                = { bg = colors.base },
                                                NoiceCmdlinePopupBorder          = { fg = colors.base, bg = colors.base },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- SNACKS

                                                SnacksPicker                     = {  bg = colors.crust },
                                                SnacksNotifierBorderInfo         = { fg = colors.crust, bg = colors.crust },
                                                SnacksNotifierBorderWarn         = { fg = colors.crust, bg = colors.crust },
                                                SnacksNotifierBorderError        = { fg = colors.crust, bg = colors.crust },
                                                SnacksNotifierFooterInfo         = { fg = colors.crust, bg = colors.crust },
                                                SnacksNotifierFooterWarn         = { fg = colors.crust, bg = colors.crust },
                                                SnacksNotifierFooterError        = { fg = colors.crust, bg = colors.crust },
                                                SnacksNotifierTitleInfo          = { bg = colors.crust },
                                                SnacksNotifierTitleWarn          = { bg = colors.crust },
                                                SnacksNotifierTitleError         = { bg = colors.crust },
                                                SnacksNotifierInfo               = { bg = colors.crust },
                                                SnacksNotifierWarn               = { bg = colors.crust },
                                                SnacksNotifierError              = { bg = colors.crust },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- MODES

                                                ModesCopyCursorLineNr            = { fg = colors.rosewater, bg = colors.crust },
                                                ModesCopyCursorLineSign          = { fg = colors.rosewater, bg = colors.crust },
                                                ModesCopyCursorLineFold          = { fg = colors.rosewater, bg = colors.crust },
                                                ModesDeleteCursorLineNr          = { fg = colors.rosewater, bg = colors.crust },
                                                ModesDeleteCursorLineSign        = { fg = colors.rosewater, bg = colors.crust },
                                                ModesDeleteCursorLineFold        = { fg = colors.rosewater, bg = colors.crust },
                                                ModesInsertCursorLineNr          = { fg = colors.rosewater, bg = colors.crust },
                                                ModesInsertCursorLineSign        = { fg = colors.rosewater, bg = colors.crust },
                                                ModesInsertCursorLineFold        = { fg = colors.rosewater, bg = colors.crust },
                                                ModesVisualCursorLineNr          = { fg = colors.rosewater, bg = colors.crust },
                                                ModesVisualCursorLineSign        = { fg = colors.rosewater, bg = colors.crust },
                                                ModesVisualCursorLineFold        = { fg = colors.rosewater, bg = colors.crust },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- BLINK

                                                BlinkCmpAbbrDeprecated           = { fg = colors.maroon, bg = "NONE", strikethrough = false },
                                                BlinkCmpAbbrMatch                = { fg = colors.text, bg = "NONE", bold = false },
                                                BlinkCmpAbbrMatchFuzzy           = { fg = colors.text, bg = "NONE", bold = false },
                                                BlinkCmpMenu                     = { fg = colors.overlay0, bg = "#11111b", bold = false },
                                                BlinkCmpKindField                = { fg = colors.rosewater, bg = "NONE" },
                                                BlinkCmpKindProperty             = { fg = colors.rosewater, bg = "NONE" },
                                                BlinkCmpKindEvent                = { fg = colors.rosewater, bg = "NONE" },
                                                BlinkCmpKindText                 = { fg = colors.lavender, bg = "NONE" },
                                                BlinkCmpKindEnum                 = { fg = colors.lavender, bg = "NONE" },
                                                BlinkCmpKindKeyword              = { fg = colors.lavender, bg = "NONE" },
                                                BlinkCmpKindConstant             = { fg = colors.yellow, bg = "NONE" },
                                                BlinkCmpKindConstructor          = { fg = colors.yellow, bg = "NONE" },
                                                BlinkCmpKindReference            = { fg = colors.yellow, bg = "NONE" },
                                                BlinkCmpKindFunction             = { fg = "#dce0e8", bg = "NONE" },
                                                BlinkCmpKindStruct               = { fg = "#dce0e8", bg = "NONE" },
                                                BlinkCmpKindClass                = { fg = "#dce0e8", bg = "NONE" },
                                                BlinkCmpKindModule               = { fg = "#dce0e8", bg = "NONE" },
                                                BlinkCmpKindOperator             = { fg = "#dce0e8", bg = "NONE" },
                                                BlinkCmpKindVariable             = { fg = colors.text, bg = "NONE" },
                                                BlinkCmpKindFile                 = { fg = colors.text, bg = "NONE" },
                                                BlinkCmpKindUnit                 = { fg = colors.yellow, bg = "NONE" },
                                                BlinkCmpKindSnippet              = { fg = colors.yellow, bg = "NONE" },
                                                BlinkCmpKindFolder               = { fg = colors.yellow, bg = "NONE" },
                                                BlinkCmpKindMethod               = { fg = colors.text, bg = "NONE" },
                                                BlinkCmpKindValue                = { fg = colors.text, bg = "NONE" },
                                                BlinkCmpKindEnumMember           = { fg = colors.text, bg = "NONE" },
                                                BlinkCmpKindInterface            = { fg = colors.teal, bg = "NONE" },
                                                BlinkCmpKindColor                = { fg = colors.teal, bg = "NONE" },
                                                BlinkCmpKindTypeParameter        = { fg = colors.teal, bg = "NONE" },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- MISC

                                                TSDefinitionUsage                = { bg = colors.surface0 },
                                                -- FloatBorder                      = { fg = colors.mantle, bg = colors.mantle },
                                                FloatBorder                      = { fg = colors.crust, bg = colors.crust },
                                                -- TSDefinition                     = { bg = colors.surface2 },
                                                Normal                           = { bg = colors.crust },
                                                NormalNC                         = { bg = colors.crust },
                                                NormalFloat                      = { fg = colors.text, bg = colors.mantle },
                                                LineNr                           = { fg = colors.surface0, bg = colors.crust },
                                                CursorLineNr                     = { fg = colors.rosewater, bg = colors.crust },
                                                SagaFileName                     = { fg = colors.rosewater, bg = colors.mantle },
                                                NoiceCmdlineIcon                 = { fg = colors.rosewater },
                                                ActiveLineNumber                 = { fg = colors.subtext0 },
                                                Title                            = { fg = colors.subtext0 },
                                                MiniClueDescSingle               = { fg = colors.subtext0, bg = colors.crust },
                                                NoiceSplit                       = { fg = colors.subtext0, bg = colors.crust },
                                                VertSplit                        = { fg = colors.base, bg = colors.crust },
                                                WinBar                           = { fg = colors.subtext0, bg = colors.mantle },
                                                WinBarNC                         = { fg = colors.subtext0, bg = colors.mantle },
                                                LspInfoBorder                    = { fg = colors.subtext0, bg = colors.subtext0 },
                                                Folded                           = { fg = colors.surface0, bg = colors.base },
                                                WinSeparator                     = { fg = colors.base, bg = colors.crust },
                                                SagaSep                          = { fg = colors.surface1, bg = colors.mantle },
                                                Visual                           = { fg = colors.red, bg = colors.mantle, bold = false },
                                                SignatureHelpBorder              = { fg = colors.mantle, bg = colors.mantle },
                                                HoverBorder                      = { fg = colors.mantle, bg = colors.mantle },
                                                RipSubBackdrop                   = { fg = colors.mantle, bg = colors.mantle },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- NEOTREE

                                                NeoTreeNormal                    = { fg = colors.text, bg = colors.crust },
                                                NeoTreeCursorLine                = { fg = "NONE", bg = colors.crust, bold = true },
                                                NeoTreeDirectoryIcon             = { fg = "#dce0e8" },
                                                NeoTreeFileName                  = { fg = colors.overlay2 },
                                                NeoTreeDirectoryName             = { fg = "#dce0e8" },
                                                NeoTreeExpander                  = { fg = colors.base },
                                                NeoTreeRootName                  = { fg = colors.flamingo },
                                                NeoTreeGitUntracked              = { fg = colors.lavender },
                                                NeoTreeGitModified               = { fg = colors.red },
                                                NeoTreeFloatTitle                = { fg = colors.crust, bg = colors.text },
                                                NeoTreeFloatBorder               = { fg = colors.text },
                                                NeoTreeFloatNormal               = { fg = colors.text },
                                                NeoTreeWinSeparator              = { fg = colors.base, bg = colors.crust },
                                                NeoTreeVertSplit                 = { fg = colors.surface0, bg = colors.crust },
                                                NeoTreeStatsHeader               = { fg = colors.base, bg = colors.base },
                                                NeoTreeModified                  = { fg = colors.text },
                                                NeoTreeNormalNC                  = { fg = colors.text, bg = colors.crust },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- TELESCOPE

                                                TelescopePromptCount             = { fg = colors.text, bg = colors.crust },
                                                TelescopePromptTitle             = { fg = colors.flamingo, bg = colors.crust },
                                                TelescopePromptPrefix            = { fg = colors.flamingo, bg = colors.crust },
                                                TelescopePromptNormal            = { fg = colors.text, bg = colors.crust },
                                                TelescopePromptBorder            = { fg = colors.crust, bg = colors.crust },
                                                TelescopeResultsTitle            = { fg = colors.flamingo, bg = colors.crust },
                                                TelescopeResultsNormal           = { fg = colors.overlay0, bg = colors.crust },
                                                TelescopeResultsBorder           = { fg = colors.crust, bg = colors.crust },
                                                TelescopePreviewTitle            = { fg = colors.text, bg = colors.crust },
                                                TelescopePreviewNormal           = { fg = colors.text, bg = colors.crust },
                                                TelescopePreviewBorder           = { fg = colors.mantle, bg = colors.crust },
                                                TelescopeSelection               = { fg = colors.red, bg = colors.crust },
                                                TelescopeSelectionCaret          = { fg = colors.red, bg = colors.crust },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- LUALINE
                                                lualine_a_insert                 = { fg = colors.crust, bg = colors.text },
                                                lualine_a_normal                 = { fg = colors.crust, bg = colors.text },
                                                lualine_a_visual                 = { fg = colors.crust, bg = colors.text },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- DROPBAR

                                                DropBarCurrentContext            = { fg = colors.overlay1 },
                                                DropBarFzfMatch                  = { fg = colors.red },
                                                DropBarHover                     = { fg = colors.overlay1 },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- OUTLINE
                                                OutlineCurrent                   = { fg = colors.flamingo, bg = colors.crust },
                                                OutlineDetails                   = { fg = colors.surface1 },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- DROPBAR ICON UI

                                                DropBarIconUiIndicator           = { fg = colors.surface1 },
                                                DropBarIconUiPickpivot           = { fg = colors.red },
                                                DropBarIconUiSeparator           = { fg = colors.surface1 },
                                                DropBarIconUiSeparatormenu       = { fg = colors.rosewater },

                                                DropBarMenuCurrentContext        = { fg = colors.red, bg = colors.base },
                                                DropBarMenuFloatBorder           = { fg = colors.rosewater, bg = colors.mantle },
                                                DropBarMenuHoverEntry            = { fg = colors.red, bg = colors.base },
                                                DropBarMenuHoverIcon             = { reverse = false, fg = colors.red, bg = colors.base },
                                                DropBarMenuHoverSymbol           = { bold = true, fg = colors.rosewater, bg = colors.base },
                                                DropBarMenuNormalFloat           = { fg = colors.rosewater, bg = colors.mantle },
                                                DropBarMenuSbar                  = { fg = colors.red, bg = colors.mantle },
                                                DropBarMenuThumb                 = { fg = colors.rosewater, bg = colors.mantle },
                                                DropBarPreview                   = { fg = colors.rosewater, bg = colors.base },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- DROPBAR KIND

                                                DropBarKindDefault               = { fg = colors.rosewater },
                                                DropBarKindArray                 = { fg = colors.rosewater },
                                                DropBarKindBoolean               = { fg = colors.peach },
                                                DropBarKindBreakstatement        = { fg = colors.lavender },
                                                DropBarKindCall                  = { fg = colors.rosewater },
                                                DropBarKindCasestatement         = { fg = colors.lavender },
                                                DropBarKindClass                 = { fg = "#dce0e8" },
                                                DropBarKindConstant              = { fg = colors.yellow },
                                                DropBarKindConstructor           = { fg = colors.yellow },
                                                DropBarKindContinuestatement     = { fg = colors.lavender },
                                                DropBarKindDeclaration           = { fg = colors.rosewater },
                                                DropBarKindDelete                = { fg = colors.red },
                                                DropBarKindDostatement           = { fg = colors.lavender },
                                                DropBarKindElsestatement         = { fg = colors.lavender },
                                                DropBarKindElement               = { fg = colors.rosewater },
                                                DropBarKindEnum                  = { fg = colors.lavender },
                                                DropBarKindEnumMember            = { fg = colors.text },
                                                DropBarKindEvent                 = { fg = colors.peach },
                                                DropBarKindField                 = { fg = colors.lavender },
                                                DropBarKindFile                  = { fg = colors.subtext0 },
                                                DropBarKindFolder                = { fg = "#dce0e8" },
                                                DropBarKindForStatement          = { fg = colors.lavender },
                                                DropBarKindFunction              = { fg = "#dce0e8" },
                                                DropBarKindH1Marker              = { fg = colors.red },
                                                DropBarKindH2Marker              = { fg = colors.peach },
                                                DropBarKindH3Marker              = { fg = colors.yellow },
                                                DropBarKindH4Marker              = { fg = colors.green },
                                                DropBarKindH5Marker              = { fg = colors.sapphire },
                                                DropBarKindH6Marker              = { fg = colors.lavender },
                                                DropBarKindIdentifier            = { fg = colors.rosewater },
                                                DropBarKindIfStatement           = { fg = colors.lavender },
                                                DropBarKindInterface             = { fg = colors.teal },
                                                DropBarKindKeyword               = { fg = colors.lavender },
                                                DropBarKindList                  = { fg = colors.rosewater },
                                                DropBarKindMacro                 = { fg = colors.mauve },
                                                DropBarKindMarkdownH1            = { fg = colors.red },
                                                DropBarKindMarkdownH2            = { fg = colors.peach },
                                                DropBarKindMarkdownH3            = { fg = colors.yellow },
                                                DropBarKindMarkdownH4            = { fg = colors.green },
                                                DropBarKindMarkdownH5            = { fg = colors.sapphire },
                                                DropBarKindMarkdownH6            = { fg = colors.lavender },
                                                DropBarKindMethod                = { fg = colors.text },
                                                DropBarKindModule                = { fg = "#dce0e8" },
                                                DropBarKindNamespace             = { fg = colors.mauve },
                                                DropBarKindNull                  = { fg = colors.peach },
                                                DropBarKindNumber                = { fg = colors.maroon },
                                                DropBarKindObject                = { fg = colors.lavender },
                                                DropBarKindOperator              = { fg = "#dce0e8" },
                                                DropBarKindPackage               = { fg = colors.sapphire },
                                                DropBarKindPair                  = { fg = colors.rosewater },
                                                DropBarKindProperty              = { fg = colors.lavender },
                                                DropBarKindReference             = { fg = colors.yellow },
                                                DropBarKindRepeat                = { fg = colors.rosewater },
                                                DropBarKindRuleset               = { fg = colors.rosewater },
                                                DropBarKindScope                 = { fg = colors.rosewater },
                                                DropBarKindSpecifier             = { fg = colors.rosewater },
                                                DropBarKindStatement             = { fg = colors.lavender },
                                                DropBarKindString                = { fg = colors.green },
                                                DropBarKindStruct                = { fg = "#dce0e8" },
                                                DropBarKindSwitchstatement       = { fg = colors.lavender },
                                                DropBarKindTerminal              = { fg = colors.rosewater },
                                                DropBarKindType                  = { fg = colors.teal },
                                                DropBarKindTypeParameter         = { fg = colors.teal },
                                                DropBarKindUnit                  = { fg = colors.yellow },
                                                DropBarKindValue                 = { fg = colors.text },
                                                DropBarKindVariable              = { fg = colors.red },
                                                DropBarKindWhileStatement        = { fg = colors.lavender },

                                                -------------------------------------------------------------------------------------------------------------
                                                -- DROPBAR ICON KIND

                                                DropBarIconKindFile              = { fg = colors.subtext0 },
                                                DropBarIconKindModule            = { fg = "#dce0e8" },
                                                DropBarIconKindNamespace         = { fg = colors.mauve },
                                                DropBarIconKindPackage           = { fg = colors.sapphire },
                                                DropBarIconKindClass             = { fg = "#dce0e8" },
                                                DropBarIconKindMethod            = { fg = colors.text },
                                                DropBarIconKindProperty          = { fg = colors.lavender },
                                                DropBarIconKindField             = { fg = colors.lavender },
                                                DropBarIconKindConstructor       = { fg = colors.yellow },
                                                DropBarIconKindEnum              = { fg = colors.lavender },
                                                DropBarIconKindInterface         = { fg = colors.teal },
                                                DropBarIconKindFunction          = { fg = "#dce0e8" },
                                                DropBarIconKindVariable          = { fg = colors.red },
                                                DropBarIconKindConstant          = { fg = colors.yellow },
                                                DropBarIconKindString            = { fg = colors.green },
                                                DropBarIconKindNumber            = { fg = colors.maroon },
                                                DropBarIconKindBoolean           = { fg = colors.peach },
                                                DropBarIconKindArray             = { fg = colors.rosewater },
                                                DropBarIconKindObject            = { fg = colors.lavender },
                                                DropBarIconKindKeyword           = { fg = colors.lavender },
                                                DropBarIconKindNull              = { fg = colors.peach },
                                                DropBarIconKindEnumMember        = { fg = colors.text },
                                                DropBarIconKindStruct            = { fg = "#dce0e8" },
                                                DropBarIconKindEvent             = { fg = colors.peach },
                                                DropBarIconKindOperator          = { fg = "#dce0e8" },
                                                DropBarIconKindTypeParameter     = { fg = colors.teal },
                                                DropBarIconKindDefault           = { fg = colors.rosewater },
                                                DropBarIconKindBreakStatement    = { fg = colors.lavender },
                                                DropBarIconKindCall              = { fg = colors.rosewater },
                                                DropBarIconKindCaseStatement     = { fg = colors.lavender },
                                                DropBarIconKindContinueStatement = { fg = colors.lavender },
                                                DropBarIconKindDeclaration       = { fg = colors.rosewater },
                                                DropBarIconKindDelete            = { fg = colors.red },
                                                DropBarIconKindDoStatement       = { fg = colors.lavender },
                                                DropBarIconKindElseStatement     = { fg = colors.lavender },
                                                DropBarIconKindElement           = { fg = colors.rosewater },
                                                DropBarIconKindFolder            = { fg = "#dce0e8" },
                                                DropBarIconKindForStatement      = { fg = colors.lavender },
                                                DropBarIconKindH1Marker          = { fg = colors.red },
                                                DropBarIconKindH2Marker          = { fg = colors.peach },
                                                DropBarIconKindH3Marker          = { fg = colors.yellow },
                                                DropBarIconKindH4Marker          = { fg = colors.green },
                                                DropBarIconKindH5Marker          = { fg = colors.sapphire },
                                                DropBarIconKindH6Marker          = { fg = colors.lavender },
                                                DropBarIconKindIdentifier        = { fg = colors.rosewater },
                                                DropBarIconKindIfstatement       = { fg = colors.lavender },
                                                DropBarIconKindList              = { fg = colors.rosewater },
                                                DropBarIconKindMacro             = { fg = colors.mauve },
                                                DropBarIconKindMarkdownH1        = { fg = colors.red },
                                                DropBarIconKindMarkdownH2        = { fg = colors.peach },
                                                DropBarIconKindMarkdownH3        = { fg = colors.yellow },
                                                DropBarIconKindMarkdownH4        = { fg = colors.green },
                                                DropBarIconKindMarkdownH5        = { fg = colors.sapphire },
                                                DropBarIconKindMarkdownH6        = { fg = colors.lavender },
                                                DropBarIconKindPair              = { fg = colors.rosewater },
                                                DropBarIconKindReference         = { fg = colors.yellow },
                                                DropBarIconKindRepeat            = { fg = colors.rosewater },
                                                DropBarIconKindRuleset           = { fg = colors.rosewater },
                                                DropBarIconKindScope             = { fg = colors.rosewater },
                                                DropBarIconKindSpecifier         = { fg = colors.rosewater },
                                                DropBarIconKindStatement         = { fg = colors.lavender },
                                                DropBarIconKindSwitchStatement   = { fg = colors.lavender },
                                                DropBarIconKindTerminal          = { fg = colors.rosewater },
                                                DropBarIconKindType              = { fg = colors.teal },
                                                DropBarIconKindUnit              = { fg = colors.yellow },
                                                DropBarIconKindValue             = { fg = colors.text },
                                                DropBarIconKindWhileStatement    = { fg = colors.lavender },

                                        }
                                end,

                                default_integrations   = true,
                                integrations           = {
                                        blink_cmp        = true,
                                        cmp              = true,
                                        dap              = true,
                                        dap_ui           = true,
                                        lsp_saga         = true,
                                        dashboard        = true,
                                        dropbar          = {
                                                enabled    = true,
                                                color_mode = true
                                        },
                                        gitsigns         = true,
                                        indent_blankline = {
                                                enabled     = true,
                                                scope_color = "text",
                                        },
                                        mason            = true,
                                        markdown         = true,
                                        render_markdown  = true,
                                        mini             = true,
                                        native_lsp       = {
                                                enabled    = true,
                                                underlines = {
                                                        -- errors      = { "undercurl" },
                                                        -- hints       = { "undercurl" },
                                                        -- warnings    = { "undercurl" },
                                                        -- information = { "undercurl" },
                                                },
                                        },
                                        telescope        = true,
                                        notify           = true,
                                        navic            = { enabled = true, custom_bg = "lualine" },
                                        neotest          = true,
                                        neotree          = true,
                                        noice            = true,
                                        semantic_tokens  = true,
                                        treesitter       = true,
                                        ufo              = true,
                                        which_key        = true,
                                },
                        })

                        vim.cmd(" colorscheme catppuccin")
                end,
        },
}
