local map = require("core.utils").uniqueKeymap

return {
        "Bekaboo/dropbar.nvim",
        lazy         = false,
        event        = "LspAttach",
        dependencies = {
                "nvim-telescope/telescope-fzf-native.nvim",
        },

        config       = function()
                require("dropbar").setup({
                        icons = {
                                enable = true,
                                kinds  = {
                                        symbols = {
                                                Array             = "󰅪 ",
                                                Boolean           = " ",
                                                BreakStatement    = "󰙧 ",
                                                Call              = "󰃷 ",
                                                CaseStatement     = "󱃙 ",
                                                Class             = " ",
                                                Color             = " ",
                                                Constant          = " ",
                                                Constructor       = " ",
                                                ContinueStatement = "→ ",
                                                Copilot           = " ",
                                                Declaration       = "󰙠 ",
                                                Delete            = "󰢤 ",
                                                DoStatement       = "󰑖 ",
                                                Enum              = " ",
                                                EnumMember        = " ",
                                                Event             = " ",
                                                Field             = " ",
                                                File              = " ",
                                                Folder            = " ",
                                                ForStatement      = "󰑖 ",
                                                Function          = " ",
                                                H1Marker          = "󰉫 ",
                                                H2Marker          = "󰉬 ",
                                                H3Marker          = "󰉭 ",
                                                H4Marker          = "󰉮 ",
                                                H5Marker          = "󰉯 ",
                                                H6Marker          = "󰉰 ",
                                                Identifier        = " ",
                                                IfStatement       = " ",
                                                Interface         = " ",
                                                Keyword           = " ",
                                                List              = "󰅪 ",
                                                Log               = " ",
                                                Lsp               = " ",
                                                Macro             = " ",
                                                MarkdownH1        = "󰉫 ",
                                                MarkdownH2        = "󰉬 ",
                                                MarkdownH3        = "󰉭 ",
                                                MarkdownH4        = "󰉮 ",
                                                MarkdownH5        = "󰉯 ",
                                                MarkdownH6        = "󰉰 ",
                                                Method            = " ",
                                                Module            = " ",
                                                Namespace         = " ",
                                                Null              = "󰢤 ",
                                                Number            = "󰎠 ",
                                                Object            = " ",
                                                Operator          = "󰆕 ",
                                                Package           = " ",
                                                Pair              = "󰅪 ",
                                                Property          = " ",
                                                Reference         = "󰈇 ",
                                                Regex             = " ",
                                                Repeat            = "󰑖 ",
                                                Scope             = " ",
                                                Snippet           = " ",
                                                Specifier         = "󰦪 ",
                                                Statement         = " ",
                                                String            = "󰉾 ",
                                                Struct            = " ",
                                                SwitchStatement   = "󰺟 ",
                                                Terminal          = " ",
                                                Text              = " ",
                                                Type              = " ",
                                                TypeParameter     = " ",
                                                Unit              = " ",
                                                Value             = "󰎠 ",
                                                Variable          = " ",
                                                WhileStatement    = "󰑖 ",
                                        },
                                },
                                ui     = {
                                        bar  = {
                                                separator = "  ",
                                                extends   = "…",
                                        },
                                        menu = {
                                                separator = "",
                                                indicator = " 󰨓  ",
                                        },
                                },
                        },
                        bar = {
                                truncate = true,
                                pick     = {
                                        pivots = "123456789abcdefghijklmnopqrstuvwxyz",
                                }
                        }
                })
        end,
        map("n", "<A-q>", function() require('dropbar.api').pick() end)
}
