return {
        "brenoprata10/nvim-highlight-colors",
        event   = "VeryLazy",
        enabled = true,
        config  = function()
                require("nvim-highlight-colors").setup({
                        render                  = "background",
                        virtual_symbol          = " 󰝤",
                        virtual_symbol_prefix   = "",
                        virtual_symbol_suffix   = " ",
                        virtual_symbol_position = "inline",
                        enable_hex              = true,
                        enable_short_hex        = false,
                        enable_rgb              = true,
                        enable_hsl              = true,
                        enable_var_usage        = true,
                        enable_named_colors     = false,
                        enable_tailwind         = true,
                        custom_colors           = {
                                { label = "colors.rosewater", color = "#f5e0dc" },
                                { label = "colors.flamingo",  color = "#f2cdcd" },
                                { label = "colors.pink",      color = "#f5c2e7" },
                                { label = "colors.mauve",     color = "#cba6f7" },
                                { label = "colors.red",       color = "#f38ba8" },
                                { label = "colors.maroon",    color = "#eba0ac" },
                                { label = "colors.peach",     color = "#fab387" },
                                { label = "colors.yellow",    color = "#f9e2af" },
                                { label = "colors.green",     color = "#a6e3a1" },
                                { label = "colors.teal",      color = "#94e2d5" },
                                { label = "colors.sky",       color = "#89dceb" },
                                { label = "colors.sapphire",  color = "#74c7ec" },
                                { label = "colors.blue",      color = "#89b4fa" },
                                { label = "colors.lavender",  color = "#b4befe" },
                                { label = "colors.text",      color = "#cdd6f4" },
                                { label = "colors.subtext1",  color = "#bac2de" },
                                { label = "colors.subtext0",  color = "#a6adc8" },
                                { label = "colors.overlay2",  color = "#9399b2" },
                                { label = "colors.overlay1",  color = "#7f849c" },
                                { label = "colors.overlay0",  color = "#6c7086" },
                                { label = "colors.surface2",  color = "#585b70" },
                                { label = "colors.surface1",  color = "#45475a" },
                                { label = "colors.surface0",  color = "#313244" },
                                { label = "colors.base",      color = "#1e1e2e" },
                                { label = "colors.mantle",    color = "#181825" },
                                { label = "colors.crust",     color = "#11111b" },
                        },
                        exclude_filetypes       = {},
                        exclude_buftypes        = {},
                })
        end,
}
