return {
        "nvim-neo-tree/neo-tree.nvim",
        event        = "VeryLazy",
        branch       = "v3.x",
        dependencies = {
                "nvim-lua/plenary.nvim",
                "nvim-tree/nvim-web-devicons",
                "MunifTanjim/nui.nvim",
        },
        config       = function()
                require("neo-tree").setup({
                        add_blank_line_at_top            = false,
                        auto_clean_after_session_restore = true,
                        close_if_last_window             = true,
                        enable_cursor_hijack             = false,
                        enable_diagnostics               = true,
                        enable_git_status                = true,
                        enable_modified_markers          = true,
                        enable_opened_markers            = true,
                        enable_refresh_on_write          = true,
                        hide_root_node                   = true,
                        open_files_do_not_replace_types  = { "terminal", "Trouble", "trouble", "qf", "Outline" },
                        retain_hidden_root_indent        = false,
                        sort_case_insensitive            = false,
                        sources                          = { "filesystem", "buffers" },
                        source_selector                  = {
                                winbar                        = false,
                                statusline                    = false,
                                show_scrolled_off_parent_node = false,
                        },
                        window                           = {
                                position          = "right",
                                width             = 30,
                                auto_expand_width = false,
                                mapping_options   = {
                                        noremap = true,
                                        nowait  = true,
                                },
                                mappings          = {
                                        ["P"] = { "toggle_preview", config = { use_float = true } },
                                        ["H"] = { "prev_source" },
                                        ["L"] = { "next_source" },
                                        ["l"] = { "open" },
                                        ["h"] = { "toggle_node" },
                                        ["a"] = { "add", config = { show_path = "none" } },
                                        ["A"] = "add_directory",
                                        ["d"] = "delete",
                                        ["r"] = "rename",
                                        ["y"] = "copy_to_clipboard",
                                        ["x"] = "cut_to_clipboard",
                                        ["p"] = "paste_from_clipboard",
                                        ["c"] = "copy",
                                        ["m"] = "move",
                                        ["q"] = "close_window",
                                        ["R"] = "refresh",
                                        ["?"] = "show_help",
                                        ["<"] = "prev_source",
                                        [">"] = "next_source",
                                        ["i"] = "show_file_details",
                                },
                        },
                        default_component_configs        = {
                                indent      = {
                                        with_expanders     = false,
                                        indent_marker      = "",
                                        last_indent_marker = "",
                                        expander_collapsed = "",
                                        expander_expanded  = "",
                                },
                                icon        = {
                                        folder_closed = "",
                                        folder_open   = "",
                                        folder_empty  = "",
                                },
                                diagnostics = {
                                        symbols    = {
                                                hint  = "󰨓",
                                                info  = "󰨓",
                                                warn  = "󰨓",
                                                error = "󰨓",
                                        },
                                        highlights = {
                                                hint  = "DiagnosticSignHint",
                                                info  = "DiagnosticSignInfo",
                                                warn  = "DiagnosticSignWarn",
                                                error = "DiagnosticSignError",
                                        },
                                },
                                modified    = {
                                        symbol    = "󰨓",
                                        highlight = "NeoTreeModified",
                                },
                        },
                        filesystem                       = {
                                filtered_items         = {
                                        visible         = true,
                                        hide_dotfiles   = false,
                                        hide_gitignored = true,
                                },
                                bind_to_cwd            = false,
                                follow_current_file    = { enabled = true },
                                leave_dirs_open        = true,
                                use_libuv_file_watcher = false,
                                terminals_first        = true,
                        },
                })
        end,
}
