--------------------------------------------------------------------------------
-- C/C++ SEMANTIC SYNTAX HIGHLIGHTING

vim.cmd(" highlight cBlock                                   guifg=#cdd6f4 ")
vim.cmd(" highlight cRepeat                                  guifg=#74c7ec ")
vim.cmd(" highlight cConditional                             guifg=#74c7ec ")
vim.cmd(" highlight cInclude                                 guifg=#f38ba8 ")

vim.cmd(" highlight @type.builtin.cpp                        guifg=#89b4fa ")
vim.cmd(" highlight @keyword.conditional.cpp                 guifg=#74c7ec ")
vim.cmd(" highlight @keyword.repeat.cpp                      guifg=#74c7ec ")
vim.cmd(" highlight @keyword.return.cpp                      guifg=#f38ba8 ")
vim.cmd(" highlight @function.cpp                            guifg=#dce0e8 ")
vim.cmd(" highlight @lsp.type.function.cpp                   guifg=#dce0e8 ")
vim.cmd(" highlight @lsp.type.method.cpp                     guifg=#dce0e8 ")
vim.cmd(" highlight @lsp.type.namespace.cpp                  guifg=#f9e2af ")
vim.cmd(" highlight @lsp.typemod.variable.defaultLibrary.cpp guifg=#f38ba8 ")
vim.cmd(" highlight @lsp.typemod.function.defaultLibrary.cpp guifg=#f38ba8 ")
vim.cmd(" highlight @lsp.typemod.variable.globalScope        guifg=#f38ba8 ")
vim.cmd(" highlight @lsp.typemod.variable.functionScope.cpp  guifg=#cba6f7 ")

vim.cmd(" highlight @keyword.conditional.c                   guifg=#74c7ec ")
vim.cmd(" highlight @keyword.repeat.c                        guifg=#74c7ec ")
vim.cmd(" highlight @keyword.return.c                        guifg=#dce0e8 ")
vim.cmd(" highlight @function.c                              guifg=#dce0e8 ")
vim.cmd(" highlight @lsp.type.function.c                     guifg=#dce0e8 ")
vim.cmd(" highlight @lsp.type.method.c                       guifg=#dce0e8 ")
vim.cmd(" highlight @lsp.type.operator.c                     guifg=#cdd6f4 ")
vim.cmd(" highlight @lsp.type.namespace.c                    guifg=#f9e2af ")
vim.cmd(" highlight @lsp.typemod.variable.defaultLibrary.c   guifg=#f38ba8 ")
vim.cmd(" highlight @lsp.typemod.function.defaultLibrary.c   guifg=#f38ba8 ")
